name: rebuild
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^7.0.0
  supabase: ^2.0.8
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.6.7
  hive: ^4.0.0-dev.2
  intl: ^0.19.0
  decimal: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
